baseurl                  = "https://lucacorsato.github.io/lc"           # Your domain name. Must end with "/"
languageCode             = "it-IT"
defaultContentLanguage   = "it"
isMultilingual           = false
title                    = "Luca Corsato"
theme                    = "sam"
pygmentsStyle            = "monokai"                        # https://help.farbox.com/pygments.html
pygmentsCodefences       = true
# googleAnalytics        = ""                               # Tracking code, eg. "UA-111111111-1"
publishDir = "docs"

[params]
    dateform             = "Mon Jan 02, 2006"
    dateformfull         = "Mon Jan 2 2006 15:04:05 EST"
    favicon              = "sam.ico"
    homepage             = "main"                           # What to call the home page link
    footerText           = "Ciao, sono Luca"

# Metadata for Open Graph and Twitter
    description          = "Sito personale di Luca Corsato"               # Max 160 characters show in search results
    images               = ["tn.png"]                       # Image that shows on Twitter cards and Open Graph links to the site
    title                = "Ciao sono Luca"


[[params.mainMenu]]
    link = "page/about"
    text = "Chi è Luca?"

[imaging]
    quality = 75
